### ISSUE TITLE
3d compatibility

### ISSUE THREAD

**Issue by faridf** [nxt-lab/GPy-DOS#1]
Thanks very much for publishing this code.

I have a question regarding dimensionality. Your examples showcase that this code works for X data that are 1d and 2d. 
Is this also compatible with X data that is 3d?

**Comment by nxtruong** [comment]
In theory yes, but this code is pretty old. I'd suggest checking out GPyTorch if supporting derivative observation is important: https://docs.gpytorch.ai/en/stable/examples/08_Advanced_Usage/Simple_GP_Regression_Derivative_Information_1d.html.
